export const TEST_SUITES = ["unit", "integration", "contract", "legacy-update", "legacy"];

export const TEST_FEATURES = [
  "covers",
  "export",
  "import",
  "image-gallery",
  "image-sections",
  "library",
  "legacy-update",
  "markdown",
  "masterpiece",
  "moments",
  "progress",
  "rating",
  "release",
  "release-tracking",
  "score-dashboard",
  "search",
  "serial-covers",
  "settings",
  "styles",
  "test-infrastructure",
  "test-vault",
  "text",
  "timeline",
  "tags",
];

export const TEST_TARGETS = [
  { path: "tests/cover-cache.test.ts", kind: "test", suite: "integration", features: ["covers"] },
  { path: "tests/media-asset-cleanup.test.ts", kind: "test", suite: "unit", features: ["covers", "image-sections", "moments", "markdown"] },
  { path: "tests/vault-trash.test.ts", kind: "test", suite: "unit", features: ["covers", "image-sections"] },
  { path: "tests/media-form-lifecycle.test.ts", kind: "test", suite: "unit", features: ["serial-covers", "settings"] },
  { path: "tests/image-gallery.test.ts", kind: "test", suite: "unit", features: ["image-gallery", "image-sections", "markdown"] },
  { path: "tests/contracts/image-gallery-service.test.ts", kind: "test", suite: "contract", features: ["image-gallery", "image-sections", "markdown", "library"] },
  { path: "tests/image-section.test.ts", kind: "test", suite: "unit", features: ["image-sections", "markdown"] },
  { path: "tests/image-section-layout.test.ts", kind: "test", suite: "unit", features: ["image-sections", "markdown"] },
  { path: "tests/image-section-drag-hit-testing.test.ts", kind: "test", suite: "unit", features: ["image-sections"] },
  { path: "tests/image-section-order-journal.test.ts", kind: "test", suite: "unit", features: ["image-sections", "markdown"] },
  { path: "tests/image-section-context-menu.test.ts", kind: "test", suite: "unit", features: ["image-sections"] },
  { path: "tests/image-clipboard.test.ts", kind: "test", suite: "unit", features: ["image-sections"] },
  { path: "tests/image-lightbox.test.ts", kind: "test", suite: "unit", features: ["image-sections"] },
  { path: "tests/contracts/image-section-service.test.ts", kind: "test", suite: "contract", features: ["image-sections", "markdown"] },

  { path: "tests/moments.test.ts", kind: "test", suite: "unit", features: ["moments", "markdown"] },
  { path: "tests/moment-image-layout.test.ts", kind: "test", suite: "unit", features: ["moments"] },
  { path: "tests/moment-stack-raster.test.ts", kind: "test", suite: "unit", features: ["moments", "image-sections"] },
  { path: "tests/media-note-insert-menu.test.ts", kind: "test", suite: "unit", features: ["moments", "image-sections"] },
  { path: "tests/contracts/moments-service.test.ts", kind: "test", suite: "contract", features: ["moments", "image-sections", "markdown"] },

  { path: "tests/masterpiece-labels.test.ts", kind: "test", suite: "unit", features: ["masterpiece"] },
  { path: "tests/masterpiece-decoration-cache.test.ts", kind: "test", suite: "unit", features: ["masterpiece", "library"] },

  { path: "tests/media-status.test.ts", kind: "test", suite: "unit", features: ["progress"] },
  { path: "tests/progress-display.test.ts", kind: "test", suite: "unit", features: ["progress"] },
  { path: "tests/progress-units.test.ts", kind: "test", suite: "unit", features: ["progress"] },
  { path: "tests/completion-date.test.ts", kind: "test", suite: "unit", features: ["progress", "timeline", "library"] },
  { path: "tests/manual-media.test.ts", kind: "test", suite: "unit", features: ["library"] },
  { path: "tests/abort.test.ts", kind: "test", suite: "unit", features: ["release-tracking"] },
  { path: "tests/release-tracking.test.ts", kind: "test", suite: "unit", features: ["release-tracking"] },
  { path: "tests/rating.test.ts", kind: "test", suite: "unit", features: ["rating", "progress"] },
  { path: "tests/release-tracking-state-service.test.ts", kind: "test", suite: "integration", features: ["release-tracking", "markdown"] },
  { path: "tests/release-tracking-enrollment.test.ts", kind: "test", suite: "integration", features: ["release-tracking", "markdown"] },
  { path: "tests/release-tracking-settings.test.ts", kind: "test", suite: "integration", features: ["release-tracking", "settings"] },
  { path: "tests/schema-migration.test.ts", kind: "test", suite: "integration", features: ["progress", "markdown"] },
  { path: "tests/segmented-date-input.test.ts", kind: "test", suite: "unit", features: ["progress"] },
  { path: "tests/serial-entry-scroll.test.ts", kind: "test", suite: "unit", features: ["progress"] },
  { path: "tests/serial-entry-keyboard-navigation.test.ts", kind: "test", suite: "unit", features: ["progress"] },

  { path: "tests/score-dashboard.test.ts", kind: "test", suite: "unit", features: ["score-dashboard", "rating"] },
  { path: "tests/score-dashboard-selection.test.ts", kind: "test", suite: "unit", features: ["score-dashboard"] },
  { path: "tests/score-dashboard-drag-scroll.test.ts", kind: "test", suite: "unit", features: ["score-dashboard"] },
  { path: "tests/score-dashboard-cover-sources.test.ts", kind: "test", suite: "unit", features: ["score-dashboard", "covers"] },

  { path: "tests/duplicate-detection.test.ts", kind: "test", suite: "unit", features: ["search"] },
  { path: "tests/library-change-scope.test.ts", kind: "test", suite: "unit", features: ["library"] },
  { path: "tests/library-progressive-render.test.ts", kind: "test", suite: "unit", features: ["library"] },
  { path: "tests/library-layout.test.ts", kind: "test", suite: "unit", features: ["library", "settings"] },
  { path: "tests/workspace-responsive.test.ts", kind: "test", suite: "unit", features: ["library", "timeline", "score-dashboard", "image-gallery", "styles"] },
  { path: "tests/mobile-swipe-isolation.test.ts", kind: "test", suite: "unit", features: ["library", "timeline", "score-dashboard", "image-gallery", "moments", "settings", "styles"] },
  { path: "tests/library-filters.test.ts", kind: "test", suite: "unit", features: ["library"] },
  { path: "tests/studio-identity.test.ts", kind: "test", suite: "unit", features: ["library", "search"] },
  { path: "tests/user-tag-catalog.test.ts", kind: "test", suite: "unit", features: ["tags"] },
  { path: "tests/user-tag-settings.test.ts", kind: "test", suite: "integration", features: ["tags", "settings"] },
  { path: "tests/media-library-index.test.ts", kind: "test", suite: "unit", features: ["library"] },
  { path: "tests/library-export.test.ts", kind: "test", suite: "unit", features: ["library", "export"] },
  { path: "tests/library-text-template.test.ts", kind: "test", suite: "unit", features: ["library", "export"] },
  { path: "tests/library-import.test.ts", kind: "test", suite: "unit", features: ["library", "import"] },
  { path: "tests/markdown-refresh-scope.test.ts", kind: "test", suite: "unit", features: ["library", "markdown"] },
  { path: "tests/library-navigation.test.ts", kind: "test", suite: "integration", features: ["search", "library"] },
  { path: "tests/library-view.test.ts", kind: "test", suite: "unit", features: ["library", "masterpiece"] },
  { path: "tests/multilingual-search.test.ts", kind: "test", suite: "unit", features: ["search"] },
  { path: "tests/search-pagination.test.ts", kind: "test", suite: "unit", features: ["search"] },
  { path: "tests/search-settings.test.ts", kind: "test", suite: "integration", features: ["search", "settings"] },

  { path: "tests/serial-entry-cover.test.ts", kind: "test", suite: "unit", features: ["serial-covers"] },
  { path: "tests/serial-cover-workflow.test.ts", kind: "test", suite: "integration", features: ["serial-covers", "timeline"] },
  { path: "tests/serial-cover-settings.test.ts", kind: "test", suite: "integration", features: ["serial-covers", "settings"] },
  { path: "tests/serial-cover-migration-modal.test.ts", kind: "test", suite: "unit", features: ["serial-covers"] },

  { path: "tests/timeline-scale.test.ts", kind: "test", suite: "integration", features: ["timeline"] },
  { path: "tests/timeline-scale-work-items.test.ts", kind: "test", suite: "unit", features: ["timeline"] },
  { path: "tests/timeline-workspace-layout.test.ts", kind: "test", suite: "unit", features: ["timeline"] },
  { path: "tests/timeline-corrections.test.ts", kind: "test", suite: "unit", features: ["timeline", "progress"] },

  { path: "tests/contracts/media-note-compatibility.test.ts", kind: "test", suite: "contract", features: ["markdown", "progress"] },
  { path: "tests/contracts/media-note-service.test.ts", kind: "test", suite: "contract", features: ["markdown", "library", "covers"] },
  { path: "tests/contracts/media-asset-garbage-collector.test.ts", kind: "test", suite: "contract", features: ["covers", "image-sections", "moments", "markdown"] },
  { path: "tests/contracts/media-update-service.test.ts", kind: "test", suite: "contract", features: ["markdown", "progress", "library"] },
  { path: "tests/contracts/user-tag-library-service.test.ts", kind: "test", suite: "contract", features: ["tags", "settings", "markdown"] },
  { path: "tests/contracts/external-media-service.test.ts", kind: "test", suite: "contract", features: ["search"] },
  { path: "tests/contracts/metadata-provider-clients.test.ts", kind: "test", suite: "contract", features: ["search"] },
  { path: "tests/contracts/release-tracking-provider-clients.test.ts", kind: "test", suite: "contract", features: ["release-tracking"] },
  { path: "tests/contracts/media-classification-service.test.ts", kind: "test", suite: "contract", features: ["search", "markdown"] },
  { path: "tests/contracts/media-classification-fields.test.ts", kind: "test", suite: "contract", features: ["search", "markdown"] },
  { path: "tests/contracts/media-quarter-metadata.test.ts", kind: "test", suite: "contract", features: ["search", "markdown", "settings"] },
  { path: "tests/contracts/legacy-metadata-cleanup.test.ts", kind: "test", suite: "legacy-update", features: ["legacy-update", "settings", "markdown", "search"] },
  { path: "tests/legacy-update/version-cleanup.test.ts", kind: "test", suite: "legacy-update", features: ["legacy-update", "settings", "markdown", "covers"] },
  { path: "tests/contracts/existing-library-initialization.test.ts", kind: "test", suite: "contract", features: ["library", "markdown", "settings"] },
  { path: "tests/contracts/feature-installer.test.ts", kind: "test", suite: "contract", features: ["test-infrastructure"] },
  { path: "tests/contracts/media-repository.test.ts", kind: "test", suite: "contract", features: ["library", "markdown"] },
  { path: "tests/contracts/plugin-workflows.test.ts", kind: "test", suite: "contract", features: ["timeline", "library"] },
  { path: "tests/contracts/settings-compatibility.test.ts", kind: "test", suite: "contract", features: ["settings", "search", "masterpiece"] },
  { path: "tests/contracts/special-label-state-service.test.ts", kind: "test", suite: "contract", features: ["masterpiece", "library"] },
  { path: "tests/contracts/style-bundle.test.ts", kind: "test", suite: "contract", features: ["styles", "release", "timeline"] },
  { path: "tests/contracts/text-catalog.test.ts", kind: "test", suite: "contract", features: ["text", "settings"] },
  { path: "tests/contracts/test-catalog.test.ts", kind: "test", suite: "contract", features: ["test-infrastructure"] },
  { path: "tests/contracts/version-metadata.test.ts", kind: "test", suite: "contract", features: ["release", "test-infrastructure"] },
  { path: "scripts/check-architecture.mjs", kind: "script", suite: "contract", features: ["test-infrastructure"] },

  { path: "tests/legacy-characterization.test.ts", kind: "test", suite: "legacy", features: ["library", "markdown", "progress", "release", "search", "settings", "text", "timeline", "serial-covers"] },
  { path: "scripts/check-serial-reading-ui.mjs", kind: "script", suite: "legacy", features: ["progress", "serial-covers", "timeline"] },
  { path: "scripts/check-library-list-layout.mjs", kind: "script", suite: "legacy", features: ["library", "covers"] },
  { path: "scripts/check-test-vault-fixtures.mjs", kind: "script", suite: "contract", features: ["test-vault", "test-infrastructure"] },
];
