export const READING_PROGRESS_TEXT = {
  command: "新增漫畫閱讀紀錄",
  title: "漫畫閱讀紀錄",
  description: "每筆紀錄可分別選擇話、季或卷。完成日期未填時會使用今天。",
  add: "新增一筆",
  empty: "尚無閱讀紀錄。",
  value: "進度",
  unit: "單位",
  startedAt: "開始日期",
  completedAt: "完成日期",
  remove: "移除",
  cancel: "取消",
  save: "儲存",
  saved: "漫畫閱讀紀錄已儲存。",
  mangaOnly: "目前筆記不是漫畫紀錄。",
  invalid: "閱讀進度格式不正確。話與季只能使用非負整數；卷可使用整數、.5 或 EX。",
  duplicate: "相同單位與進度的紀錄不可重複。",
  unitChapter: "話",
  unitSeason: "季",
  unitVolume: "卷",
} as const;
