import { defineTextCatalog } from "./i18n/catalog";

const MESSAGES = {
  title: "分數表",
  kicker: "SCORE DASHBOARD",
  description: "依個人評分整理作品；每個作品只顯示一張代表封面。",
  open: "開啟分數表",
  all: "所有",
  anime: "動畫",
  manga: "漫畫",
  novel: "小說",
  unrated: "未評分",
  showUnrated: "顯示未評分",
  hideUnrated: "隱藏未評分",
  zoom: "縮放",
  emptyLane: "尚無作品",
  works: "部作品",
  batchSelect: "批次選取",
  finishBatch: "完成選取",
  batchShort: "批次",
  finishBatchShort: "完成",
  selected: "已選 {count} 部",
  selectVisible: "全選目前顯示",
  clearSelection: "清除選取",
  moveTo: "移動至…",
  shiftDown: "降低 0.5",
  shiftUp: "提高 0.5",
  cancel: "取消",
  confirmClamp: "確認並限制在範圍內",
  shiftClampTitle: "部分分數會超出範圍",
  shiftClampMessage: "這次調整有 {count} 部作品會超出 0～10。確認後會自動限制為 0 或 10。",
  shiftClampLow: "{count} 部會限制為 0 分",
  shiftClampHigh: "{count} 部會限制為 10 分",
  shiftBlockedUnrated: "選取中有 {count} 部未評分作品。未評分作品不能使用提高／降低，請先直接移到指定分數。",
  moveSuccess: "已更新 {count} 部作品的分數。",
  moveNoChange: "作品已在目標分數，沒有需要更新的項目。",
  moveFailed: "分數更新失敗：{message}",
  dragHint: "拖曳封面可直接變更分數",
  selectionHint: "點選封面勾選作品，再使用批次工具列移動。",
  ratedSummary: "已評分 {rated}／{total}",
  coverAlt: "{title} 的封面",
  unratedControlLabel: "{action}，{count} 部作品",
  posterAria: "{title}，{score}",
  scoreLaneAria: "{score} 分",
  noteMissing: "找不到作品筆記：{path}",
  rollbackFailed: "；回復失敗：{paths}",
  rollbackSucceeded: "；已回復先前變更",
  updateFailed: "更新分數失敗：{reason}{rollback}",
} as const;

const CATALOG = defineTextCatalog("score-dashboard", MESSAGES);
const text = <K extends keyof typeof MESSAGES>(key: K, variables: Record<string, string | number> = {}) => (
  CATALOG.text(key, variables)
);

export const scoreDashboardText = {
  get title() { return text("title"); },
  get kicker() { return text("kicker"); },
  get description() { return text("description"); },
  get open() { return text("open"); },
  get all() { return text("all"); },
  get anime() { return text("anime"); },
  get manga() { return text("manga"); },
  get novel() { return text("novel"); },
  get unrated() { return text("unrated"); },
  get showUnrated() { return text("showUnrated"); },
  get hideUnrated() { return text("hideUnrated"); },
  get zoom() { return text("zoom"); },
  get emptyLane() { return text("emptyLane"); },
  get works() { return text("works"); },
  get batchSelect() { return text("batchSelect"); },
  get finishBatch() { return text("finishBatch"); },
  get batchShort() { return text("batchShort"); },
  get finishBatchShort() { return text("finishBatchShort"); },
  selected: (count: number) => text("selected", { count }),
  get selectVisible() { return text("selectVisible"); },
  get clearSelection() { return text("clearSelection"); },
  get moveTo() { return text("moveTo"); },
  get shiftDown() { return text("shiftDown"); },
  get shiftUp() { return text("shiftUp"); },
  get cancel() { return text("cancel"); },
  get confirmClamp() { return text("confirmClamp"); },
  get shiftClampTitle() { return text("shiftClampTitle"); },
  shiftClampMessage: (low: number, high: number) => text("shiftClampMessage", { count: low + high }),
  shiftClampLow: (count: number) => text("shiftClampLow", { count }),
  shiftClampHigh: (count: number) => text("shiftClampHigh", { count }),
  shiftBlockedUnrated: (count: number) => text("shiftBlockedUnrated", { count }),
  moveSuccess: (count: number) => text("moveSuccess", { count }),
  get moveNoChange() { return text("moveNoChange"); },
  moveFailed: (message: string) => text("moveFailed", { message }),
  get dragHint() { return text("dragHint"); },
  get selectionHint() { return text("selectionHint"); },
  ratedSummary: (rated: number, total: number) => text("ratedSummary", { rated, total }),
  coverAlt: (title: string) => text("coverAlt", { title }),
  unratedControlLabel: (action: string, count: number) => text("unratedControlLabel", { action, count }),
  posterAria: (title: string, score: string) => text("posterAria", { title, score }),
  scoreLaneAria: (score: string) => text("scoreLaneAria", { score }),
  noteMissing: (path: string) => text("noteMissing", { path }),
  rollbackFailed: (paths: string) => text("rollbackFailed", { paths }),
  get rollbackSucceeded() { return text("rollbackSucceeded"); },
  updateFailed: (reason: string, rollback: string) => text("updateFailed", { reason, rollback }),
} as const;
